version: '3.8'

services:

  logi-postgres:
    image: postgres:17-alpine
    container_name: logi-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - logi-postgres-data:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.8.5
    ports:
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:9092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:29092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - kafka-data:/var/lib/kafka/data

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
    depends_on:
      - kafka

  order-service:
    build:
      context: .
      dockerfile: order/Dockerfile
    container_name: order-service
    depends_on:
      logi-postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "18085:18085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped

  product-service:
    build:
      context: .
      dockerfile: product/Dockerfile
    container_name: product-service
    depends_on:
      logi-postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "18084:18084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped

  payment-service:
    build:
      context: .
      dockerfile: payment/Dockerfile
    container_name: payment-service
    depends_on:
      logi-postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "18087:18087"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped

volumes:
  logi-postgres-data:
    driver: local
  redis-data:
    driver: local
  kafka-data:
    driver: local