server:
  port: 18083

spring:
  application:
    name: hub-service

  datasource:
    # 기본값: 로컬 PostgreSQL
    url: ${USER_SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hub_db}
    username: ${USER_SPRING_DATASOURCE_USERNAME:user}
    password: ${USER_SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: hub_service
    show-sql: true

eureka:
  client:
    service-url:
      # 기본값: 로컬 유레카 서버
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.logistics.user: DEBUG
    org.hibernate.SQL: DEBUG