server:
  port: 18084

spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://logi-postgres:5432/product_db
    username: user
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: product_service
    show_sql: true
    defer-datasource-initialization: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: product-service
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

eureka:
  client:
    enabled: false
