server:
  port: 18085

spring:
  application:
    name: order-service

  datasource:
    url: ${USER_SPRING_DATASOURCE_URL}
    username: ${USER_SPRING_DATASOURCE_USERNAME}
    password: ${USER_SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: order_service
    show-sql: false