server:
  port: 18085

spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://logi-postgres:5432/order_db
    username: user
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: order_service
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: order-service
eureka:
  client:
    enabled: false
