server:
  port: 18085

spring:
  application:
    name: order-service

  datasource:
    # 기본값: 로컬 PostgreSQL
    url: ${USER_SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/order_db}
    username: ${USER_SPRING_DATASOURCE_USERNAME:user}
    password: ${USER_SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: order_service
    show-sql: true

eureka:
  client:
    service-url:
      # 기본값: 로컬 유레카 서버
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.logistics.order: DEBUG
    org.hibernate.SQL: DEBUG

gemini:
  base-url: https://generativelanguage.googleapis.com
  model: gemini-2.5-flash
  api-key: AIzaSyDULwOtFhMZ0e5550UgS3veZqGzx-nMSMA