eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

jwt:
  secret: ${JWT_SECRET}
  expiration-time: 3600000

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: WARN
    org.springframework.cloud.gateway: INFO
    com.logistics.gateway: INFO