server:
  port: 18086

spring:
  datasource:
    url: ${DELIVERY_SPRING_DATASOURCE_URL}
    username: ${DELIVERY_SPRING_DATASOURCE_USERNAME}
    password: ${DELIVERY_SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: delivery_service
    show_sql: true