CREATE DATABASE order_db;
GRANT ALL PRIVILEGES ON DATABASE order_db TO "user";

CREATE DATABASE product_db;
GRANT ALL PRIVILEGES ON DATABASE product_db TO "user";

CREATE DATABASE payment_db;
GRANT ALL PRIVILEGES ON DATABASE payment_db TO "user";