server:
  port: 18082

spring:
  application:
    name: company-service

  datasource:
    url: ${COMPANY_SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/company_db}
    username: ${COMPANY_SPRING_DATASOURCE_USERNAME:user}
    password: ${COMPANY_SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: company_service
        hbm2ddl:
          create_namespaces: true
    show-sql: true

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: FULL

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.logistics.company: DEBUG
    org.hibernate.SQL: DEBUG