services:
  delivery-postgres:
    image: postgres:15-alpine
    container_name: delivery-postgres
    environment:
      - POSTGRES_DB=delivery_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - TZ=Asia/Seoul
    ports:
      - "5436:5436"
    volumes:
      - delivery-postgres-data:/var/lib/postgresql/data
    networks:
      - delivery-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d delivery_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  delivery-service:
    build:
      context: ..
      dockerfile: delivery/Dockerfile
      platforms:
        - linux/amd64
    image: delivery-service:latest
    container_name: delivery-service
    environment:
        - SPRING_PROFILES_ACTIVE=local
        - DELIVERY_SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/delivery_db
        - DELIVERY_SPRING_DATASOURCE_USERNAME=user
        - DELIVERY_SPRING_DATASOURCE_PASSWORD=1234
    ports:
      - "18086:18086"
    depends_on:
      delivery-postgres:
        condition: service_healthy
    networks:
      - delivery-network
    restart: unless-stopped

volumes:
  delivery-postgres-data:
    driver: local

networks:
  delivery-network:
    driver: bridge
  msa-network:
    external: true